# Generated by Django 4.2.7 on 2023-12-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
