# Generated by Django 4.2.7 on 2023-12-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_alter_user_bio_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('email', models.CharField(max_length=200, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=200, verbose_name='Téléphone')),
                ('subject', models.CharField(max_length=200, verbose_name='Sujet')),
                ('message', models.TextField()),
            ],
        ),
    ]
