# Generated by Django 4.2.7 on 2023-12-22 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('bio', models.CharField(max_length=1000, verbose_name='Biographie')),
                ('phone', models.CharField(max_length=200, verbose_name='Téléphone')),
                ('verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Profil',
            },
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Contactez-nous'},
        ),
    ]
