# Generated by Django 4.2.7 on 2023-12-03 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cartorderitems_options_alter_wishlist_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='core.category', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='En vedette'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('desactiver', 'Désactivé'), ('rejeter', 'Rejeté'), ('en_revue', 'En revue'), ('publier', 'Publié')], default='en_revue', max_length=15, verbose_name='Statut du produit'),
        ),
    ]
