# Generated by Django 4.2.7 on 2023-12-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product_life_product_mfd_product_stock_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='authentic_rating',
            field=models.CharField(default='100', max_length=150),
        ),
    ]
