# Generated by Django 4.2.7 on 2023-12-22 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('account_number', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=10, max_length=25, prefix='127', unique=True, verbose_name='Numéro de compte')),
                ('account_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=7, max_length=25, prefix='kf', unique=True, verbose_name='Identifiant de compte')),
                ('pin_number', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=4, max_length=7, prefix='', unique=True, verbose_name='Code PIN')),
                ('ref_code', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh1234567890', length=10, max_length=25, prefix='', unique=True, verbose_name='code de référence')),
                ('account_status', models.CharField(choices=[('actif', 'Actif'), ('en-attente', 'En attente'), ('inactif', 'Inactif')], default='inactif', max_length=150, verbose_name='Statut du compte')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('kyc_submitted', models.BooleanField(default=False)),
                ('kyc_confirmed', models.BooleanField(default=False)),
                ('recommended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='recommended_by', to=settings.AUTH_USER_MODEL, verbose_name='Recommandé par')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name_plural': 'Comptes',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ClientTerrain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('image', models.ImageField(default='default.jpg', upload_to='clientTerrain')),
                ('marrital_status', models.CharField(choices=[('marier', 'Marié(e)'), ('celibataire', 'Célibataire')], max_length=100, verbose_name='Situation Matrimoniale')),
                ('gender', models.CharField(choices=[('masculin', 'Masculin'), ('feminin', 'Feminin')], max_length=100, verbose_name='Genre')),
                ('identity_type', models.CharField(choices=[('carte_didentite_nationale', "Carte d'identité nationale"), ('permis_de_conduire', 'Permis de conduire'), ('passeport_international', 'Passeport international')], max_length=150, verbose_name="Type d'identité")),
                ('identity_image', models.ImageField(blank=True, null=True, upload_to='clientTerrain', verbose_name='Identité image')),
                ('date_of_birth', models.DateTimeField(verbose_name='Date de naissance')),
                ('signature', models.ImageField(upload_to='clientTerrain')),
                ('country', models.CharField(max_length=100, verbose_name='Pays')),
                ('state', models.CharField(max_length=100, verbose_name='État')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('mobile', models.CharField(max_length=100, verbose_name='Téléphone')),
                ('fax', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prefinancement.account', verbose_name='Compte')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='ClientContruction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('image', models.ImageField(default='default.jpg', upload_to='clientConstruction')),
                ('marrital_status', models.CharField(choices=[('marier', 'Marié(e)'), ('celibataire', 'Célibataire')], max_length=100, verbose_name='Situation Matrimoniale')),
                ('gender', models.CharField(choices=[('masculin', 'Masculin'), ('feminin', 'Feminin')], max_length=100, verbose_name='Genre')),
                ('identity_type', models.CharField(choices=[('carte_didentite_nationale', "Carte d'identité nationale"), ('permis_de_conduire', 'Permis de conduire'), ('passeport_international', 'Passeport international')], max_length=150, verbose_name="Type d'identité")),
                ('identity_image', models.ImageField(blank=True, null=True, upload_to='clientConstruction', verbose_name='Identité image')),
                ('date_of_birth', models.DateTimeField(verbose_name='Date de naissance')),
                ('signature', models.ImageField(upload_to='clientConstruction')),
                ('documents', models.ImageField(upload_to='clientConstruction')),
                ('country', models.CharField(max_length=100, verbose_name='Pays')),
                ('state', models.CharField(max_length=100, verbose_name='État')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('mobile', models.CharField(max_length=100, verbose_name='Téléphone')),
                ('fax', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prefinancement.account', verbose_name='Compte')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
        ),
    ]
